### ISSUE TITLE
Project license missing.

### ISSUE THREAD

**Issue by athanasiosem** [fkereki/NodeJsRestful#2]
Please put a license in your project so we can know what is permitted to do with it.

**Comment by fkereki** [comment]
Hi! I don't know enough about licenses, but usage is free -- check out the README file I just added. The code was (at least partly) included in my articles at Wazi, so it's readily available. I'd appreciate it if you let me know about any errors, problems, enhancements, etc., you found. Good luck, and enjoy!

**Comment by athanasiosem** [comment]
Hello. A good site to learn about Open Source licenses is http://choosealicense.com/ . Please choose a license and include a LICENSE file in your project so we can download it and use it. Thanks.
